### PR TITLE
Eslint rules Frontend

### PR DESCRIPTION
**Pull request by fanckush**
this is just the FE part of:
https://trello.com/c/kcNCbOUi/57-linter-enforcement

### CODE REVIEW

**Review by Filip-Zafran — COMMENTED** [review]
Hey, 
Im getting some errors when I am trying to log in:
1. I cant log in with the Demo account
2. When I log in with my account:
`Error: Objects are not valid as a React child (found: object with keys {name, message, stack}). If you meant to render a collection of children, use an array instead.`

**Review by HelenHMaher — APPROVED** [review]
I went through all the files and tbh just checked the ones that I have written.  So most of the "Profile" feature I can't necessarily vouch for, but everything looks good that I saw.  Just syntax changes and cleaning up some warnings that were bugging my anyways (thanks for doing this, I love how clean the console finally is and that we have a standard formatter).

I got some interesting bugs when I navigated through the profile section and then back to the "swiping" section and I'm not sure where this is coming from.  I will look into it more.  We have a few pesky bugs hanging around that just need to be tracked down, but I am happy for this to be committed so we can have standards moving forward.

**Comment by HelenHMaher** [comment]
> Hey,
> Im getting some errors when I am trying to log in:
> 
> 1. I cant log in with the Demo account
> 2. When I log in with my account:
>    `Error: Objects are not valid as a React child (found: object with keys {name, message, stack}). If you meant to render a collection of children, use an array instead.`

I wasn't able to duplicate this error.  I'm not sure what could be going on.  My first guess would always be to make sure you're on the latest version of the backend but if that's not the problem we'll have to figure it out because I don't see how any of the changes here should be creating this error (but there's always that possibility >_<)

**Comment by fanckush** [comment]
Cool, I'll go ahead and merge this then

**Pull request merged**
