### PR TITLE
Register

### PR DESCRIPTION
**Pull request by Edith2019**
Please look at

index.js file with the new routes for the APP
Welcome.js page (we should be where users end up if no registration). It is not working yet as we need to implement cookies from the backend I think. However, if you take the url: http://localhost:3000/Welcome#/ you will see it.
Registration page that gather the data from input fields and send them to backend with the route /register

### CODE REVIEW

**Comment by FilipNew1234** [comment]
What I would def like to have before merging - is to clear all errors. 

But very nice comment explanations :)

**Comment by Edith2019** [comment]
> What I would def like to have before merging - is to clear all errors.
> 
> But very nice comment explanations :)

What error do you talk about?

**Comment by FilipNew1234** [comment]
> > What I would def like to have before merging - is to clear all errors.
> > But very nice comment explanations :)
> 
> What error do you talk about?

Yeah, all is good. 
Dont forget to NPM INSTALL before NPM START

**Review by FilipNew1234 — APPROVED** [review]
Looks good

**Review by HelenHMaher — APPROVED** [review]
Looks good to me

**Pull request merged**
